import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";


const nunito = Nunito({

  subsets: ["latin"],

  weight: [
    "300",
    "400",
    "500",
    "600",
    "700",
    "800"
  ],

  display: "swap",

  variable: "--font-nunito",

});


export const metadata: Metadata = {

  title: "Dashboard",

  description: "Generated by create next app",

};



export default function RootLayout({

  children,

}: Readonly<{

  children: React.ReactNode;

}>) {


  return (

    <html

      lang="en"

      suppressHydrationWarning

      className={`
        ${nunito.variable}
        h-full
        antialiased
      `}

    >


      <body

        className="
          min-h-screen

          bg-background

          text-foreground

          overflow-x-hidden
        "

      >

        <ThemeProvider>

          {children}

        </ThemeProvider>


      </body>


    </html>

  );

}